apiVersion: apps/v1
kind: Deployment
metadata:
  name: pxc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pxc-client
  template:
    metadata:
      labels:
        name: pxc-client
    spec:
      containers:
      - name: pxc-client
        image: perconalab/percona-xtradb-cluster-operator:0.4.0-backup
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /etc/mysql/ssl
          name: ssl
      volumes:
        - name: ssl
          secret:
            defaultMode: 420
            optional: false
            secretName: some-name-ssl
