apiVersion: v1
data:
  init.cnf: |
    [mysqld]
    wsrep_debug=ON
    max_allowed_packet=789M
    [sst]
    wsrep_debug=ON
kind: ConfigMap
metadata:
  name: no-proxysql-pxc
  ownerReferences:
  - apiVersion: pxc.percona.com/v1
    controller: true
    kind: PerconaXtraDBCluster
    name: no-proxysql
