apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: no-proxysql
    app.kubernetes.io/name: percona-xtradb-cluster
  name: no-proxysql-pxc
  ownerReferences:
  - apiVersion: pxc.percona.com/v1alpha1
    controller: true
    kind: PerconaXtraDBCluster
    name: no-proxysql
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/component: pxc
    app.kubernetes.io/instance: no-proxysql
    app.kubernetes.io/name: percona-xtradb-cluster
  sessionAffinity: None
  type: ClusterIP
