apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: pxc
    cluster: no-proxysql
  name: no-proxysql-pxc-nodes
  ownerReferences:
  - apiVersion: pxc.percona.com/v1alpha1
    controller: true
    kind: PerconaXtraDBCluster
    name: no-proxysql
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    component: no-proxysql-pxc-nodes
  sessionAffinity: None
  type: ClusterIP
