apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  name: some-name-proxysql
  ownerReferences:
  - apiVersion: pxc.percona.com/v1alpha1
    controller: true
    kind: PerconaXtraDBCluster
    name: some-name
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pxc
      cluster: some-name
      component: some-name-proxysql
  serviceName: some-name-proxysql-unready
  template:
    metadata:
      labels:
        app: pxc
        cluster: some-name
        component: some-name-proxysql
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pxc
              - key: cluster
                operator: In
                values:
                - some-name
              - key: component
                operator: In
                values:
                - some-name-proxysql
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root
              name: my-cluster-secrets
        - name: PROXY_ADMIN_USER
          value: proxyadmin
        - name: PROXY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: proxyadmin
              name: my-cluster-secrets
        - name: MONITOR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monitor
              name: my-cluster-secrets
        imagePullPolicy: Always
        name: proxysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        - containerPort: 6032
          name: proxyadm
          protocol: TCP
        resources:
          limits:
            cpu: 700m
            memory: 1G
          requests:
            cpu: 100m
            memory: 100M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/proxysql
          name: proxydata
          subPath: data
      - args:
        - /usr/bin/peer-list
        - -on-change=/usr/bin/add_pxc_nodes.sh
        - -service=$(PXC_SERVICE)
        env:
        - name: PXC_SERVICE
          value: some-name-pxc
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root
              name: my-cluster-secrets
        - name: PROXY_ADMIN_USER
          value: proxyadmin
        - name: PROXY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: proxyadmin
              name: my-cluster-secrets
        - name: MONITOR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monitor
              name: my-cluster-secrets
        imagePullPolicy: Always
        name: pxc-monit
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - /usr/bin/peer-list
        - -on-change=/usr/bin/add_proxysql_nodes.sh
        - -service=$(PROXYSQL_SERVICE)
        env:
        - name: PROXYSQL_SERVICE
          value: some-name-proxysql-unready
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root
              name: my-cluster-secrets
        - name: PROXY_ADMIN_USER
          value: proxyadmin
        - name: PROXY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: proxyadmin
              name: my-cluster-secrets
        - name: MONITOR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monitor
              name: my-cluster-secrets
        imagePullPolicy: Always
        name: proxysql-monit
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
        - 99
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: proxydata
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 2Gi
    status:
      phase: Pending
