apiVersion: pxc.percona.com/v1alpha1
kind: PerconaXtraDBCluster
metadata:
  name: emptydir
spec:
  secretsName: my-cluster-secrets
  pxc:
    size: 3
    image: perconalab/percona-xtradb-cluster-operator:0.4.0-pxc
    volumeSpec:
      emptyDir: {}
  proxysql:
    enabled: false
  pmm:
    enabled: false
