apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: emptydir
spec:
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  pxc:
    size: 3
    image: -pxc
    volumeSpec:
      emptyDir: {}
  proxysql:
    enabled: false
  pmm:
    enabled: false
