apiVersion: "pxc.percona.com/v1alpha1"
kind: "PerconaXtraDBCluster"
metadata:
  name: no-requests
spec:
  secretsName: my-cluster-secrets
  pxc:
    size: 3
    image: perconalab/pxc-openshift:0.2.0
    resources:
      limits:
        memory: 500M
        cpu: 300m
    volumeSpec:
      emptyDir: {}
#      hostPath:
#        path: /data
#        type: Directory
      persistentVolumeClaim:
#        storageClassName: standard
#        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 6Gi
    affinity:
      antiAffinityTopologyKey: none
  proxysql:
    enabled: true
    size: 1
    image: perconalab/proxysql-openshift:0.2.0
    resources:
      limits:
        memory: 500M
        cpu: 300m
    volumeSpec:
      emptyDir: {}
#      hostPath:
#        path: /data
#        type: Directory
      persistentVolumeClaim:
#        storageClassName: standard
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 6Gi
            memory: 1G
            cpu: 600m
          limits:
            memory: 1G
            cpu: 700m
    affinity:
      antiAffinityTopologyKey: none
  pmm:
    enabled: false
    image: perconalab/pmm-client:1.17.0
    serverHost: monitoring-service
    serverUser: pmm
