apiVersion: "pxc.percona.com/v1"
kind: "PerconaXtraDBCluster"
metadata:
  name: no-requests
spec:
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  sslInternalSecretName: some-name-ssl-internal
  pxc:
    size: 3
    image: perconalab/percona-xtradb-cluster-operator:0.4.0-pxc
    resources:
      limits:
        memory: 500M
        cpu: 300m
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6Gi
    affinity:
      antiAffinityTopologyKey: none
  proxysql:
    enabled: true
    size: 1
    image: perconalab/percona-xtradb-cluster-operator:0.4.0-proxysql
    resources:
      limits:
        memory: 500M
        cpu: 300m
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 6Gi
    affinity:
      antiAffinityTopologyKey: none
  pmm:
    enabled: false
    image: perconalab/pmm-client:1.17.1
    serverHost: monitoring-service
    serverUser: pmm
