apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  labels:
    app: pxc
    cluster: scaling-proxysql
    component: scaling-proxysql-proxysql
  name: proxydata-scaling-proxysql-proxysql-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
