apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
  name: backup1
spec:
  pxcCluster: cluster1
  storageName: fs-pvc
#  schedulerName: custom-scheduler
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: kubernetes.io/e2e-az-name
#            operator: In
#            values:
#            - e2e-az1
#            - e2e-az2
#  tolerations:
#    - effect: NoSchedule
#      key: dedicated
#      operator: Equal
#      value: storage
