apiVersion: "pxc.percona.com/v1alpha1"
kind: "PerconaXtraDBBackup"
metadata:
  name: "backup1"
spec:
  pxcCluster: "cluster1"
  volume:
    persistentVolumeClaim:
      # storageClassName: standard
      # accessModes: [ "ReadWriteOnce" ]
      # resources:
      #   requests:
      #     storage: 6Gi
