apiVersion: pxc.percona.com/v1alpha1
kind: PerconaXtraDBCluster
metadata:
  name: scheduled-backup
spec:
  secretsName: my-cluster-secrets
  pxc:
    size: 3
    image: perconalab/percona-xtradb-cluster-operator:0.4.0-pxc
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
  proxysql:
    enabled: true
    size: 1
    image: perconalab/percona-xtradb-cluster-operator:0.4.0-proxysql
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
  pmm:
    enabled: false
