apiVersion: v1
kind: Service
metadata:
  labels:
    app: pxc
    cluster: another-name
  name: another-name-pxc-proxysql
  ownerReferences:
  - apiVersion: pxc.percona.com/v1alpha1
    controller: true
    kind: PerconaXtraDBCluster
    name: another-name
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: proxyadm
    port: 6032
    protocol: TCP
    targetPort: 6032
  selector:
    component: another-name-pxc-proxysql
  sessionAffinity: None
  type: ClusterIP
