apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  name: emptydir-pxc
  ownerReferences:
  - apiVersion: pxc.percona.com/v1alpha1
    controller: true
    kind: PerconaXtraDBCluster
    name: emptydir
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pxc
      cluster: emptydir
      component: emptydir-pxc
  serviceName: emptydir-pxc
  template:
    metadata:
      labels:
        app: pxc
        cluster: emptydir
        component: emptydir-pxc
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pxc
              - key: cluster
                operator: In
                values:
                - emptydir
              - key: component
                operator: In
                values:
                - emptydir-pxc
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: PXC_SERVICE
          value: emptydir-pxc-unready
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root
              name: my-cluster-secrets
        - name: XTRABACKUP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: xtrabackup
              name: my-cluster-secrets
        - name: MONITOR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monitor
              name: my-cluster-secrets
        - name: CLUSTERCHECK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: clustercheck
              name: my-cluster-secrets
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /usr/bin/clustercheck.sh
          failureThreshold: 3
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: pxc
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/bin/clustercheck.sh
          failureThreshold: 5
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 15
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: datadir
        - mountPath: /etc/mysql/conf.d/
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
        - 99
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: datadir
      - configMap:
          defaultMode: 420
          name: emptydir-pxc
          optional: true
        name: config-volume
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
