apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  generation: 1
  name: some-name-pxc-ca
  ownerReferences:
    controller: true
    kind: PerconaXtraDBCluster
    name: some-name
spec:
  selfSigned: {}
