apiVersion: batch/v1
kind: Job
metadata:
  labels:
    cluster: sec-context
    job-name: sec-context-xb-on-demand-backup-pvc
    type: xtrabackup
  name: sec-context-xb-on-demand-backup-pvc
  ownerReferences:
  - apiVersion: pxc.percona.com/v1
    controller: true
    kind: PerconaXtraDBClusterBackup
    name: on-demand-backup-pvc
spec:
  backoffLimit: 6
  completions: 1
  manualSelector: true
  parallelism: 1
  selector:
    matchLabels:
      cluster: sec-context
      job-name: sec-context-xb-on-demand-backup-pvc
      type: xtrabackup
  template:
    metadata:
      labels:
        cluster: sec-context
        job-name: sec-context-xb-on-demand-backup-pvc
        type: xtrabackup
    spec:
      containers:
      - command:
        - bash
        - /usr/bin/backup.sh
        env:
        - name: BACKUP_DIR
          value: /backup
        - name: PXC_SERVICE
          value: sec-context-pxc
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root
              name: my-cluster-secrets
        imagePullPolicy: Always
        name: xtrabackup
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /backup
          name: xtrabackup
        - mountPath: /etc/mysql/ssl
          name: ssl
        - mountPath: /etc/mysql/ssl-internal
          name: ssl-internal
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
        - 1001
        - 1002
        - 1003
      terminationGracePeriodSeconds: 30
      volumes:
      - name: xtrabackup
        persistentVolumeClaim:
          claimName: sec-context-xb-on-demand-backup-pvc
      - name: ssl
        secret:
          defaultMode: 420
          optional: true
          secretName: some-name-ssl
      - name: ssl-internal
        secret:
          defaultMode: 420
          optional: true
          secretName: some-name-ssl-internal
