apiVersion: "pxc.percona.com/v1alpha1"
kind: "PerconaXtraDBCluster"
metadata:
  name: "cluster1"
  finalizers:
    - delete-pxc-pods-in-order
#    - delete-proxysql-pvc
#    - delete-pxc-pvc
spec:
  secretsName: my-cluster-secrets
  pxc:
    size: 3
    allowUnsafeConfigurations: false
    image: perconalab/pxc-openshift:0.2.0
#    configuration: |
#      [mysqld]
#      wsrep_debug=ON
#      [sst]
#      wsrep_debug=ON
#    imagePullSecrets:
#      - name: private-registry-credentials
#    priorityClassName: high-priority
#    annotations:
#      iam.amazonaws.com/role: role-arn
#    labels:
#      rack: rack-22
    resources:
      requests:
        memory: 1G
        cpu: 600m
#      limits:
#        memory: 1G
#        cpu: "1"
#    nodeSelector:
#      disktype: ssd
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
#      advanced:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: kubernetes.io/e2e-az-name
#                operator: In
#                values:
#                - e2e-az1
#                - e2e-az2
#    tolerations: 
#    - key: "node.alpha.kubernetes.io/unreachable"
#      operator: "Exists"
#      effect: "NoExecute"
#      tolerationSeconds: 6000
    volumeSpec:
      emptyDir:
      hostPath:
        # path: /data
        # type: Directory
      persistentVolumeClaim:
        # storageClassName: standard
        # accessModes: [ "ReadWriteOnce" ]
        # resources:
        #   requests:
        #     storage: 6Gi
      
  proxysql:
    enabled: true
    size: 1
    image: perconalab/proxysql-openshift:0.2.0
#    imagePullSecrets:
#      - name: private-registry-credentials
#    annotations:
#      iam.amazonaws.com/role: role-arn
#    labels:
#      rack: rack-22
    resources:
      requests:
        memory: 1G
        cpu: 600m
#      limits:
#        memory: 1G
#        cpu: 700m
#    priorityClassName: high-priority
#    nodeSelector:
#      disktype: ssd
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
#      advanced:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: kubernetes.io/e2e-az-name
#                operator: In
#                values:
#                - e2e-az1
#                - e2e-az2
#    tolerations:
#    - key: "node.alpha.kubernetes.io/unreachable"
#      operator: "Exists"
#      effect: "NoExecute"
#      tolerationSeconds: 6000
    volumeSpec:
      emptyDir:
      hostPath:
        # path: /data
        # type: Directory
      persistentVolumeClaim:
        # storageClassName: standard
        # accessModes: [ "ReadWriteOnce" ]
        # resources:
        #   requests:
        #     storage: 2Gi
  pmm:
    enabled: false
    image: perconalab/pmm-client:1.17.0
    serverHost: monitoring-service
    serverUser: pmm
  backup:
    image: perconalab/backupjob-openshift:0.2.0
#    imagePullSecrets:
#      - name: private-registry-credentials
    schedule:
      - name: "sat-night-backup"
        schedule: "0 0 * * 6"
        keep: 3
        volume:
          persistentVolumeClaim:
            # storageClassName: standard
            # accessModes: [ "ReadWriteOnce" ]
            # resources:
            #   requests:
            #     storage: 6Gi
