apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  labels:
    app: pxc
    cluster: no-limits
    component: no-limits-pxc
  name: datadir-no-limits-pxc-4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
