apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  name: no-requests-no-limits-pxc-proxysql
  ownerReferences:
  - apiVersion: pxc.percona.com/v1alpha1
    controller: true
    kind: PerconaXtraDBCluster
    name: no-requests-no-limits
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pxc
      cluster: no-requests-no-limits
      component: no-requests-no-limits-pxc-proxysql
  serviceName: no-requests-no-limits-pxc-proxysql
  template:
    metadata:
      labels:
        app: pxc
        cluster: no-requests-no-limits
        component: no-requests-no-limits-pxc-proxysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root
              name: my-cluster-secrets
        - name: MYSQL_PROXY_USER
          value: proxyuser
        - name: MYSQL_PROXY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: proxyuser
              name: my-cluster-secrets
        - name: MONITOR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monitor
              name: my-cluster-secrets
        - name: PXCSERVICE
          value: no-requests-no-limits-pxc-nodes
        imagePullPolicy: Always
        name: proxysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        - containerPort: 6032
          name: proxyadm
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/proxysql
          name: proxydata
          subPath: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
        - 99
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: proxydata
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
    status:
      phase: Pending
