apiVersion: apps/v1
kind: StatefulSet
metadata:
  generation: 1
  labels:
    app: pxc
    cluster: scheduled-backup
    component: scheduled-backup-pxc-nodes
  name: scheduled-backup-pxc-node
  ownerReferences:
  - apiVersion: pxc.percona.com/v1alpha1
    controller: true
    kind: PerconaXtraDBCluster
    name: scheduled-backup
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pxc
      cluster: scheduled-backup
      component: scheduled-backup-pxc-nodes
  serviceName: scheduled-backup-pxc-nodes
  template:
    metadata:
      labels:
        app: pxc
        cluster: scheduled-backup
        component: scheduled-backup-pxc-nodes
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pxc
              - key: cluster
                operator: In
                values:
                - scheduled-backup
              - key: component
                operator: In
                values:
                - scheduled-backup-pxc-nodes
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root
              name: my-cluster-secrets
        - name: XTRABACKUP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: xtrabackup
              name: my-cluster-secrets
        - name: MONITOR_PASSWORD
          valueFrom:
            secretKeyRef:
              key: monitor
              name: my-cluster-secrets
        - name: CLUSTERCHECK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: clustercheck
              name: my-cluster-secrets
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /usr/bin/clustercheck.sh
          failureThreshold: 3
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: node
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/bin/clustercheck.sh
          failureThreshold: 5
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 15
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: datadir
        - mountPath: /etc/mysql/conf.d/
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        supplementalGroups:
        - 99
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: pxc
          optional: true
        name: config-volume
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    status:
      phase: Pending
