apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: pitr-job-on-demand-backup-gcp-cs-demand-backup-1
  name: pitr-job-on-demand-backup-gcp-cs-demand-backup
spec:
  backoffLimit: 4
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: pitr-job-on-demand-backup-gcp-cs-demand-backup
    spec:
      containers:
      - command:
        - sleep
        - "10000"
        env:
        - name: S3_BUCKET_URL
          value: operator-testing/demand-backup-2020-12-03-09:05:22-full
        - name: ENDPOINT
          value: https://storage.googleapis.com
        - name: DEFAULT_REGION
          value: us-east-1
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: gcp-cs-secret
        - name: SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: gcp-cs-secret
        - name: PXC_SERVICE
          value: demand-backup-pxc
        - name: PXC_USER
          value: xtrabackup
        - name: PXC_PASS
          valueFrom:
            secretKeyRef:
              key: xtrabackup
              name: my-cluster-secrets
        - name: BINLOG_S3_ENDPOINT
          value: https://storage.googleapis.com
        - name: BINLOG_S3_REGION
          value: us-east-1
        - name: BINLOG_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: gcp-cs-secret
        - name: BINLOG_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: gcp-cs-secret
        - name: PITR_RECOVERY_TYPE
          value: latest
        - name: BINLOG_S3_BUCKET_URL
          value: operator-testing/binlog-cluster1
        - name: PITR_GTID_SET
        - name: PITR_DATE
        - name: XB_USE_MEMORY
          value: "750000000"
        image: perconalab/percona-xtradb-cluster-operator:k8spxc-482-collector-1
        imagePullPolicy: Always
        name: xtrabackup
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            memory: 1G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
        - 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30