apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backup-client
  template:
    metadata:
      labels:
        name: backup-client
    spec:
      containers:
      - name: backup-client
        image: percona/percona-xtradb-cluster-operator:0.3.0-backup
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /backup
          name: backup
      volumes:
      - name: backup
        persistentVolumeClaim:
          claimName: some-name-xb-on-demand-backup-pvc
