apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: monitoring
spec:
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  pxc:
    size: 3
    image: perconalab/percona-xtradb-cluster-operator:0.4.0-pxc
    resources:
      requests:
        memory: 500M
        cpu: 300m
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
    affinity:
      antiAffinityTopologyKey: none
  proxysql:
    enabled: true
    size: 1
    image: perconalab/percona-xtradb-cluster-operator:0.4.0-proxysql
    resources:
      requests:
        memory: 500M
        cpu: 300m
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
    affinity:
      antiAffinityTopologyKey: none
  pmm:
    enabled: true
    image: perconalab/pmm-client:1.17.1
    serverHost: monitoring-service
