apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: percona-xtradb-cluster-operator-workload-role
rules:
- apiGroups:
  - security.openshift.io 
  resources:
  - securitycontextconstraints 
  verbs:
  - use
  resourceNames:
  - privileged
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: service-account-percona-xtradb-cluster-operator-workload
subjects:
- kind: ServiceAccount
    name: percona-xtradb-cluster-operator-workload
roleRef:
  kind: ClusterRole
  name: percona-xtradb-cluster-operator-workload-role
  apiGroup: rbac.authorization.k8s.io
        
